# Generated by Django 6.0.7 on 2026-08-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_student_prefix_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mj_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Major   ",
                "verbose_name_plural": "Majors",
            },
        ),
    ]
