# Generated by Django 6.0.7 on 2026-08-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="web.major"
            ),
        ),
        migrations.AlterField(
            model_name="major",
            name="mj_name",
            field=models.CharField(max_length=100),
        ),
    ]
